name: Arduino CI

on:
  push:
    paths:
      - "**.ino"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: List directories content
        run: |
          dir "D:\a\AAC-Joystick-code\"
          dir "D:\a\AAC-Joystick-code\AAC-Joystick-code\"
          dir "D:\a\AAC-Joystick-code\AAC-Joystick-code\AAC-Joystick-code\"
      - name: Setup arduino-cli
        uses: arduino/setup-arduino-cli@v1.1.2
      - name: Install libraries
        run: |
          arduino-cli lib install Mouse
      - name: Compile Arduino Code
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli compile --fqbn arduino:avr:leonardo AAC-Joystick-code\joystickCode.ino

